const file = {
  consts: [
    ["color", "primary", 1, "mat-elevation-z6"],
    ["mat-button", "", 2, "height", "0", "position", "absolute"],
    [
      "mat-subheader",
      "",
      "translate",
      "",
      "fxHide",
      "",
      "fxShow.lt-md",
      "",
      1,
      "side-subHeader",
    ],
    ["fxHide", "", "fxShow.lt-md", ""],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/login",
      "aria-label",
      "Go to login page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "aria-label",
      "Go to user profile",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/accounting",
      "aria-label",
      "Go to accounting page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "class",
      "parent",
      "aria-label",
      "Show Orders and Payment Menu",
      3,
      "click",
      4,
      "ngIf",
    ],
    ["class", "submenu", 3, "ngClass", 4, "ngIf"],
    [
      "class",
      "parent",
      "aria-label",
      "Show Privacy and Security Menu",
      3,
      "click",
      4,
      "ngIf",
    ],
    ["mat-list-item", "", "aria-label", "Logout", 3, "click", 4, "ngIf"],
    ["mat-subheader", "", "translate", "", 1, "side-subHeader"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/contact",
      "aria-label",
      "Go to contact us page",
      3,
      "click",
    ],
    [1, "material-icons"],
    [1, "menu-text", "truncate"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/complain",
      "aria-label",
      "Go to complain page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/about",
      "aria-label",
      "Go to about us page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/photo-wall",
      "aria-label",
      "Go to photo wall",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/deluxe-membership",
      "aria-label",
      "Go to deluxe membership page",
      3,
      "click",
      4,
      "ngIf",
    ],
    ["style", "margin-bottom: 10px;", 4, "ngIf"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/score-board",
      "aria-label",
      "Open score-board",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "aria-label",
      "Launch beginners tutorial",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "href",
      "./redirect?to=https://github.com/bkimminich/juice-shop",
      "aria-label",
      "Go to OWASP Juice Shop GitHub page",
      4,
      "ngIf",
    ],
    [1, "appVersion"],
    [2, "font-size", "13px"],
    [2, "font-size", "12px"],
    [2, "margin-top", "10px"],
    [1, "icon-angular"],
    [1, "icon-html5"],
    [1, "icon-sass"],
    [1, "icon-css3"],
    [1, "icon-javascript-alt"],
    [1, "icon-nodejs"],
    [1, "icon-database-alt2"],
    [1, "icon-mongodb"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/login",
      "aria-label",
      "Go to login page",
      3,
      "click",
    ],
    ["mat-list-item", "", "aria-label", "Go to user profile", 3, "click"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/accounting",
      "aria-label",
      "Go to accounting page",
      3,
      "click",
    ],
    ["aria-label", "Show Orders and Payment Menu", 1, "parent", 3, "click"],
    [1, "menu-button", 3, "ngClass"],
    [1, "submenu", 3, "ngClass"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/order-history",
      "aria-label",
      "Go to order history page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/recycle",
      "aria-label",
      "Go to recycling page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/address/saved",
      "aria-label",
      "Go to saved address page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/saved-payment-methods",
      "aria-label",
      "Go to saved payment methods page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/wallet",
      "aria-label",
      "Go to wallet page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/order-history",
      "aria-label",
      "Go to order history page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/recycle",
      "aria-label",
      "Go to recycling page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/address/saved",
      "aria-label",
      "Go to saved address page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/saved-payment-methods",
      "aria-label",
      "Go to saved payment methods page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/wallet",
      "aria-label",
      "Go to wallet page",
      3,
      "click",
    ],
    ["aria-label", "Show Privacy and Security Menu", 1, "parent", 3, "click"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/privacy-policy",
      "aria-label",
      "Go to privacy policy page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/data-export",
      "aria-label",
      "Go to data export page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/erasure-request",
      "aria-label",
      "Go to data subject page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/change-password",
      "aria-label",
      "Go to change password page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/two-factor-authentication",
      "aria-label",
      "Go to two factor authentication page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/last-login-ip",
      "aria-label",
      "Go to last login ip page",
      3,
      "click",
      4,
      "ngIf",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/privacy-policy",
      "aria-label",
      "Go to privacy policy page",
      3,
      "click",
    ],
    ["translate", "", 1, "menu-text", "truncate"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/data-export",
      "aria-label",
      "Go to data export page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/erasure-request",
      "aria-label",
      "Go to data subject page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/change-password",
      "aria-label",
      "Go to change password page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/two-factor-authentication",
      "aria-label",
      "Go to two factor authentication page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "privacy-security/last-login-ip",
      "aria-label",
      "Go to last login ip page",
      3,
      "click",
    ],
    ["mat-list-item", "", "aria-label", "Logout", 3, "click"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/complain",
      "aria-label",
      "Go to complain page",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/deluxe-membership",
      "aria-label",
      "Go to deluxe membership page",
      3,
      "click",
    ],
    [2, "margin-bottom", "10px"],
    [
      "mat-list-item",
      "",
      "routerLink",
      "/score-board",
      "aria-label",
      "Open score-board",
      3,
      "click",
    ],
    ["matListIcon", "", 1, "fas", "fa-trophy", "fa-lg"],
    [
      "mat-list-item",
      "",
      "aria-label",
      "Launch beginners tutorial",
      3,
      "click",
    ],
    [
      "mat-list-item",
      "",
      "href",
      "./redirect?to=https://github.com/bkimminich/juice-shop",
      "aria-label",
      "Go to OWASP Juice Shop GitHub page",
    ],
    ["matListIcon", "", 1, "fab", "fa-github", "fa-lg"],
  ],
};
